package com.example.entities.model
import com.google.gson.annotations.SerializedName

data class Currencies (

	@SerializedName("AED") val aED : Double,
	@SerializedName("ARS") val aRS : Double,
	@SerializedName("AUD") val aUD : Double,
	@SerializedName("AZN") val aZN : Double,
	@SerializedName("BDT") val bDT : Double,
	@SerializedName("BHD") val bHD : Double,
	@SerializedName("BOB") val bOB : Double,
	@SerializedName("BRL") val bRL : Double,
	@SerializedName("BYN") val bYN : Double,
	@SerializedName("CAD") val cAD : Double,
	@SerializedName("CHF") val cHF : Double,
	@SerializedName("CLP") val cLP : Double,
	@SerializedName("CNY") val cNY : Double,
	@SerializedName("COP") val cOP : Double,
	@SerializedName("CRC") val cRC : Double,
	@SerializedName("DKK") val dKK : Double,
	@SerializedName("DZD") val dZD : Double,
	@SerializedName("EGP") val eGP : Double,
	@SerializedName("EUR") val eUR : Double,
	@SerializedName("GBP") val gBP : Double,
	@SerializedName("HKD") val hKD : Double,
	@SerializedName("ILS") val iLS : Double,
	@SerializedName("INR") val iNR : Double,
	@SerializedName("IQD") val iQD : Double,
	@SerializedName("JOD") val jOD : Double,
	@SerializedName("JPY") val jPY : Double,
	@SerializedName("KGS") val kGS : Double,
	@SerializedName("KRW") val kRW : Double,
	@SerializedName("KWD") val kWD : Double,
	@SerializedName("KZT") val kZT : Double,
	@SerializedName("LBP") val lBP : Double,
	@SerializedName("LKR") val lKR : Double,
	@SerializedName("MAD") val mAD : Double,
	@SerializedName("MXN") val mXN : Double,
	@SerializedName("MYR") val mYR : Double,
	@SerializedName("NOK") val nOK : Double,
	@SerializedName("NZD") val nZD : Double,
	@SerializedName("OMR") val oMR : Double,
	@SerializedName("PAB") val pAB : Double,
	@SerializedName("PEN") val pEN : Double,
	@SerializedName("PHP") val pHP : Double,
	@SerializedName("PKR") val pKR : Double,
	@SerializedName("QAR") val qAR : Double,
	@SerializedName("RUB") val rUB : Double,
	@SerializedName("SAR") val sAR : Double,
	@SerializedName("SEK") val sEK : Double,
	@SerializedName("SGD") val sGD : Double,
	@SerializedName("THB") val tHB : Double,
	@SerializedName("TND") val tND : Double,
	@SerializedName("TRY") val tRY : Double,
	@SerializedName("TWD") val tWD : Double,
	@SerializedName("USD") val uSD : Double,
	@SerializedName("ENC") val eNC : Int
)